# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_Deposito.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class T_Deposito(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.valor = QtWidgets.QLineEdit(self.centralwidget)
        self.valor.setGeometry(QtCore.QRect(210, 120, 211, 41))
        self.valor.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF;\n"
"    border-radius: 10px;\n"
"}")
        self.valor.setObjectName("valor")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(230, 30, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.titulo.setObjectName("titulo")
        self.buttonDepositar = QtWidgets.QPushButton(self.centralwidget)
        self.buttonDepositar.setGeometry(QtCore.QRect(360, 220, 89, 41))
        self.buttonDepositar.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"}")
        self.buttonDepositar.setObjectName("buttonDepositar")
        self.buttonMenu = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMenu.setGeometry(QtCore.QRect(190, 220, 89, 41))
        self.buttonMenu.setStyleSheet("QPushButton{\n"
"   color: #FFF;\n"
"}")
        self.buttonMenu.setObjectName("buttonMenu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela de Depósito"))
        self.valor.setPlaceholderText(_translate("MainWindow", "R$ 0,00"))
        self.titulo.setText(_translate("MainWindow", "Depósito"))
        self.buttonDepositar.setText(_translate("MainWindow", "Depositar"))
        self.buttonMenu.setText(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = T_Deposito()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
