# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class T_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(52, 101, 164);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #fff;")
        self.label.setObjectName("label")
        self.cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.cpf.setGeometry(QtCore.QRect(190, 150, 261, 31))
        self.cpf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cpf.setObjectName("cpf")
        self.entrar = QtWidgets.QPushButton(self.centralwidget)
        self.entrar.setGeometry(QtCore.QRect(190, 250, 261, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.entrar.setFont(font)
        self.entrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.entrar.setStyleSheet("color: rgb(255, 255, 255);")
        self.entrar.setObjectName("entrar")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 290, 231, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border: none;\n"
"color:#FFF;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.senha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha.setGeometry(QtCore.QRect(190, 200, 261, 31))
        self.senha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.senha.setObjectName("senha")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela de Login"))
        self.label.setText(_translate("MainWindow", "BANCO"))
        self.cpf.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.entrar.setText(_translate("MainWindow", "ENTRAR"))
        self.pushButton_2.setText(_translate("MainWindow", "Não tem uma conta? Registre-se"))
        self.senha.setPlaceholderText(_translate("MainWindow", "Senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = T_Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
